export const orderKey = (orderId: string) => `order:${orderId}`;
export const driverKey = (id: string) => `driver:${id}`;
export const queueKey = () => `queue:orders`;
export const driverOnlineKey = () => `drivers:online`;
export const driverLastSeenKey = () => `drivers:lastseen`;
export const geoDriverKey = () => `geo:drivers`;
export const rankDishesKey = () => `rank:dishes`;
export const menuKey = (restaurantId: string) => `menu:${restaurantId}`;
export const dishKey = (dishId: string) => `dish:${dishId}`;
export const driverHeartbeatKey = (id: string) => `driver:${id}:heartbeat`;
